module:cluster:
- sklearn_dual/cluster/**/*

module:common:
- sklearn_dual/common/**/*

module:compose:
- sklearn_dual/compose/**/*

module:covariance:
- sklearn_dual/covariance/**/*

module:cross_decomposition:
- sklearn_dual/cross_decomposition/**/*

module:datasets:
- sklearn_dual/datasets/**/*

module:decomposition:
- sklearn_dual/decomposition/**/*

module:ensemble:
- sklearn_dual/ensemble/**/*

module:feature_extraction:
- sklearn_dual/feature_extraction/**/*

module:feature_selection:
- sklearn_dual/feature_selection/**/*

module:gaussian_process:
- sklearn_dual/gaussian_process/**/*

module:impute:
- sklearn_dual/impute/**/*

module:inspection:
- sklearn_dual/inspection/**/*

module:linear_model:
- sklearn_dual/linear_model/**/*

module:manifold:
- sklearn_dual/manifold/**/*

module:metrics:
- sklearn_dual/metrics/**/*

module:mixture:
- sklearn_dual/mixture/**/*

module:model_selection:
- sklearn_dual/model_selection/**/*

module:naive_bayes:
- sklearn_dual/naive_bayes.py

module:neighbors:
- sklearn_dual/neighbors/**/*

module:neural_network:
- sklearn_dual/neural_network/**/*

module:pipeline:
- sklearn_dual/pipeline.py

module:preprocessing:
- sklearn_dual/preprocessing/**/*

module:semi_supervised:
- sklearn_dual/semi_supervised/**/*

module:svm:
- sklearn_dual/svm/**/*

module:tree:
- sklearn_dual/tree/**/*

module:utils:
- sklearn_dual/utils/**/*
