name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:  
    # Matrix for OS and Python version
    strategy:
      matrix:
        os: [ubuntu-latest]
        # , macos-latest]
        #, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
        # exclude:
        #     - os: windows-latest
        #       python-version: '3.9'
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: pip install --upgrade pip setuptools wheel meson ninja cython

      # Install OpenBLAS/LAPACK where needed
      - name: Install SciPy dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libopenblas-dev liblapack-dev gfortran

      - name: Install OpenBLAS on macOS
        if: runner.os == 'macOS'
        run: |
          brew install openblas
          export OPENBLAS=$(brew --prefix openblas)
          export CFLAGS="-I$OPENBLAS/include"
          export LDFLAGS="-L$OPENBLAS/lib"

      # Install SciPy from source on Windows only if needed
      - name: Install SciPy from wheel (Windows)
        if: runner.os == 'Windows'
        run: pip install scipy

      # For Linux/macOS, install from source to get .pxd files
      - name: Install SciPy from source
        if: runner.os != 'Windows'
        run: "pip install --no-binary :all: scipy"

      - name: Install cibuildwheel
        run: pip install cibuildwheel
      - name: Build wheels
        # cibuildwheel automatically detects OS and Python version
        run: cibuildwheel --output-dir wheelhouse
        env:
          CIBW_ARCHS_WINDOWS: AMD64   # only build 64-bit wheels
          CIBW_ARCHS_LINUX: x86_64   # only build 64-bit wheels
          CIBW_ARCHS_MACOS: x86_64   # only build 64-bit wheels
      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: wheelhouse/*.whl