name: Build Wheels

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:  
    # Matrix for OS and Python version
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
  
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Upgrade pip
        run: pip install --upgrade pip setuptools wheel meson ninja cython

      - name: Install SciPy from wheel
        run: pip install scipy

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Build wheels (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
          New-Item -ItemType Directory -Force -Path C:\b
          robocopy . C:\b /MIR
          cibuildwheel --output-dir wheelhouse C:\b
        env:
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_WINDOWS: AMD64

      - name: Build wheels for MacOS and Linux
        run: cibuildwheel --output-dir wheelhouse
        if: matrix.os != 'windows-latest'
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_ARCHS_MACOS: x86_64
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp*"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl